name: learn-github-actions

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - run: npm install ci
      - run: git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx)$' | xargs -I % sh -c 'git show ":%" | npx eslint --stdin --stdin-filename "%";'
  test-pr:
    runs-on: ubuntu-latest
    env:
      rport: ${{ secrets.RPORT }}
      rhost: ${{ secrets.RHOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6'
          redis-port: 6090
      - run: npm install ci
      - run: npm test