name: learn-github-actions

on:
  pull_request:
    branches: [ master ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    env:
      rport: ${{ secrets.RPORT }}
      rhost: ${{ secrets.RHOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
          cache: 'npm'
      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6'
          redis-port: 6090
      - run: npm install ci
      - name: Hello world action step
        id: hello
        uses: TubbyStubby/lint-pr-action@v0.0.1
        with:
          who-to-greet: 'XYZ'
      - run: npm test