name: learn-github-actions

on:
  pull_request:
    branches: [ master ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up env
        env:
            rport: ${{ secrets.RPORT }}
            rhost: ${{ secrets.RHOST }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6'
          redis-port: 6090
      - run: npm install ci
      - run: npm test