name: learn-github-actions

on:
  pull_request:
    branches: [ master ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: '6'
      - run: npm install ci
      - run: npm test