name: learn-github-actions

on:
  pull_request:
    branches: [ master ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    env:
      rport: ${{ secrets.RPORT }}
      rhost: ${{ secrets.RHOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
          cache: 'npm'
      - run: npm install ci
      - uses: TubbyStubby/testing-gh-action@v0.0.2
        with:
          who-to-greet: 'This Guy'
          